// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutohideController from "./autohide_controller.js"
application.register("autohide", AutohideController)

import HandleFormController from "./handle_form_controller.js"
application.register("handle-form", HandleFormController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import MobileViewController from "./mobile_view_controller.js"
application.register("mobile-view", MobileViewController)
